// Requests Reducer
export const FETCH_PROJECTS_REQUEST = "FETCH_PROJECTS_REQUEST";
export const CREATE_PROJECT_REQUEST = "CREATE_PROJECT_REQUEST";
export const EDIT_PROJECT_REQUEST = "EDIT_PROJECT_REQUEST";

// Menu Action Types
export const TOGGLE_MOBILE_MENU = "TOGGLE_MOBILE_MENU";
export const TOGGLE_DESKTOP_MENU = "TOGGLE_DESKTOP_MENU";

// Theme Action Types
export const TOGGLE_THEME = "TOGGLE_THEME";

// Projects Action Types
export const FETCH_PROJECTS = "FETCH_PROJECTS";
export const CREATE_PROJECT = "CREATE_PROJECT";
export const EDIT_PROJECT = "EDIT_PROJECT";
export const SAVE_SELECTED_PROJECT = "SAVE_SELECTED_PROJECT";
